FROM ubuntu:18.04

LABEL maintainer="poloniodavide@gmail.com"

ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

RUN apt-get update && apt-get install -y \
   libcurl4-openssl-dev \
   cmake \
   libjsoncpp-dev \
   openjdk-8-jdk \
   build-essential \
   wget \
   git \
   pkg-config \
   libboost-all-dev && \
   rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/oktal/pistache.git --recursive && \
   cd pistache && \
   mkdir build && \
   cd build && \
   cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .. -DCMAKE_INSTALL_PREFIX=/usr/ && \
   make && \
   make install/strip && \
   ldconfig

RUN mkdir -p /build/
VOLUME /build/
WORKDIR /build/

COPY builder.sh /usr/bin/builder
ENTRYPOINT ["builder"]
