FROM ubuntu:16.04

LABEL maintainer="poloniodavide@gmail.com"

RUN apt-get update && apt-get install -y \
    autotools-dev \
    automake \
    autoconf \
    build-essential \
    wget \
    libboost-all-dev \
    libpcap-dev \
    libssl-dev \
    libjsoncpp-dev \
    openjdk-8-jdk-headless \
    cmake \
    git && \
    wget https://github.com/Augugrumi/libviface/releases/download/v1.1.1/libviface_1.0.0.deb && \
    dpkg -i libviface_1.0.0.deb && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/mfontanini/libtins.git && \
    cd libtins && \
    mkdir build && \
    cd build && \
    cmake ../ -DLIBTINS_ENABLE_CXX11=1 && \
    make && \
    make install && \
    ldconfig

RUN git clone https://github.com/LaKabane/libtuntap.git && \
    cd libtuntap && \
    mkdir build && \
    cd build && \
    cmake ../ -DENABLE_CXX=true && \
    make && \
    make install && \
    ldconfig

RUN mkdir -p /build/
VOLUME /build/
WORKDIR /build/

COPY builder.sh /usr/bin/builder
ENTRYPOINT ["builder"]
